---
abstract: 'a mocking library for Test::Spec'
author:
  - 'Kjell-Magne Øierud <kjellm@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300024, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Spec-RMock
requires:
  Test::Spec: 0.46
version: 0.003
